package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

require("tests.mouse_state_test")
require("tests.numlock_store_test")
require("tests.hud_test")
require("tests.mouse_test")
require("tests.numpad_passthrough_test")
require("tests.numlock_sound_test")
require("tests.sound_test")
require("tests.sound_assets_test")
require("tests.compat_test")
require("tests.installer_test")
require("tests.uninstaller_test")
require("tests.verifier_test")
require("tests.telemetry_test")
require("tests.telemetry_runtime_diagnostic_test")
require("tests.telemetry_collector_test")
require("tests.system_monitor_plugin_test")
require("tests.reinstall_safety_test")
require("tests.json_test")
require("tests.project_model_test")
require("tests.folder_browser_test")
require("tests.project_config_test")
require("tests.project_discovery_test")
require("tests.project_state_test")
require("tests.project_search_test")
require("tests.project_cache_test")
require("tests.project_types_test")
require("tests.project_actions_test")
require("tests.adapters_test")
require("tests.action_executor_test")
require("tests.launcher_protocol_test")
require("tests.project_launcher_cli_test")
require("tests.project_launcher_qml_test")
require("tests.project_launcher_binding_test")
require("tests.launcher_installer_test")

require("tests.testlib").run()