local t = require("tests.testlib")

local function read_file(path)
  local file = assert(io.open(path, "r"), "missing file: " .. path)
  local content = file:read("*a")
  file:close()
  return content
end

t.test("system monitor manifest declares service and bar widget", function()
  local manifest = read_file("omarchy/plugins/gendbyte.system-monitor/manifest.json")
  t.truthy(manifest:find('"id": "gendbyte.system-monitor"', 1, true))
  t.truthy(manifest:find('"service"', 1, true))
  t.truthy(manifest:find('"bar-widget"', 1, true))
  t.truthy(manifest:find('"service": "Service.qml"', 1, true))
  t.truthy(manifest:find('"barWidget": "BarWidget.qml"', 1, true))
  t.truthy(manifest:find('"defaultSection": "right"', 1, true))
  t.truthy(manifest:find('"allowMultiple": false', 1, true))
end)

t.test("system monitor service owns one streaming collector", function()
  local service = read_file("omarchy/plugins/gendbyte.system-monitor/Service.qml")
  t.truthy(service:find("Process {", 1, true))
  t.truthy(service:find("SplitParser", 1, true))
  t.truthy(service:find("acceptSample", 1, true))
  t.truthy(service:find('"v1"', 1, true))
  t.truthy(service:find("collectorHealthy", 1, true))
  t.truthy(service:find("telemetry-collector.lua", 1, true))
  t.truthy(service:find("restartTimer", 1, true))
end)

t.test("system monitor service parses extended telemetry fields", function()
  local service = read_file("omarchy/plugins/gendbyte.system-monitor/Service.qml")
  t.truthy(service:find("cpuGhz", 1, true))
  t.truthy(service:find("memoryUsedGib", 1, true))
  t.truthy(service:find("memoryTotalGib", 1, true))
  t.truthy(service:find("gpuPercent", 1, true))
  t.truthy(service:find("networkRxBps", 1, true))
  t.truthy(service:find("networkTxBps", 1, true))
  t.truthy(service:find("values.cpu_ghz", 1, true))
  t.truthy(service:find("values.mem_used_gib", 1, true))
  t.truthy(service:find("values.mem_total_gib", 1, true))
  t.truthy(service:find("values.gpu", 1, true))
  t.truthy(service:find("values.net_rx_bps", 1, true))
  t.truthy(service:find("values.net_tx_bps", 1, true))
end)

t.test("system monitor service expires stale telemetry", function()
  local service = read_file("omarchy/plugins/gendbyte.system-monitor/Service.qml")
  t.truthy(service:find("staleTimer", 1, true))
  t.truthy(service:find("hasCpu = false", 1, true))
  t.truthy(service:find("hasCpuFrequency = false", 1, true))
  t.truthy(service:find("hasMemory = false", 1, true))
  t.truthy(service:find("hasMemorySize = false", 1, true))
  t.truthy(service:find("hasGpu = false", 1, true))
  t.truthy(service:find("hasNetwork = false", 1, true))
  t.truthy(service:find("hasTemperature = false", 1, true))
  t.truthy(service:find("staleTimer.restart()", 1, true))
end)

t.test("system monitor bar widget resolves the singleton service", function()
  local host = read_file("omarchy/plugins/gendbyte.system-monitor/ServiceHost.js")
  t.truthy(host:find('serviceFor("gendbyte.system-monitor")', 1, true))
end)

t.test("plugin collector launcher resolves repository root without duplicating telemetry", function()
  local launcher = read_file("omarchy/plugins/gendbyte.system-monitor/telemetry-collector.lua")
  local runtime = read_file("telemetry-collector.lua")
  t.truthy(launcher:find("HYPRLAND_CONFIG_ROOT", 1, true))
  t.truthy(launcher:find("dofile", 1, true))
  t.truthy(launcher:find("../../../", 1, true))
  t.truthy(runtime:find('rawget(_G, "HYPRLAND_CONFIG_ROOT")', 1, true))
end)

t.test("system monitor topbar shows extended summary and launches Activity", function()
  local widget = read_file("omarchy/plugins/gendbyte.system-monitor/BarWidget.qml")
  t.truthy(widget:find("BarWidget {", 1, true))
  t.truthy(widget:find("ServiceHost.hostedService(bar)", 1, true))
  t.truthy(widget:find('"CPU "', 1, true))
  t.truthy(widget:find('"GHz"', 1, true))
  t.truthy(widget:find('"RAM "', 1, true))
  t.truthy(widget:find('"GB"', 1, true))
  t.truthy(widget:find('"GPU "', 1, true))
  t.truthy(widget:find('"↓"', 1, true))
  t.truthy(widget:find("↑", 1, true))
  t.truthy(widget:find("formatRate", 1, true))
  t.truthy(widget:find('"°C"', 1, true))
  t.truthy(widget:find("vertical", 1, true))
  t.truthy(widget:find("omarchy-launch-or-focus-tui", 1, true))
  t.truthy(widget:find('"btop"', 1, true))
  t.truthy(widget:find("showTooltip", 1, true))
  t.truthy(widget:find("hideTooltip", 1, true))
end)
