local t = require("tests.testlib")

local function read(path)
  local file = assert(io.open(path, "r"), "missing file: " .. path)
  local content = file:read("*a")
  file:close()
  return content
end

local function contains(text, value)
  t.truthy(text:find(value, 1, true), "missing: " .. value)
end

local function excludes(text, value)
  t.eq(text:find(value, 1, true), nil, "unexpected: " .. value)
end

t.test("workspace overview shell exposes isolated IPC lifecycle", function()
  local shell = read("quickshell/gendbyte-workspace-overview/shell.qml")

  contains(shell, "gendbyte-workspace-overview")
  contains(shell, "IpcHandler")
  contains(shell, "function toggle()")
  contains(shell, "function show()")
  contains(shell, "function toggleSwitcher()")
  contains(shell, "function showSwitcher()")
  contains(shell, "function hide()")
  contains(shell, "function ping()")
end)

t.test("workspace overview uses Hyprland and one-shot Wayland previews", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")
  local preview = read("quickshell/gendbyte-workspace-overview/components/WindowPreview.qml")

  contains(overview, "import Quickshell.Hyprland")
  contains(overview, "WlrLayershell.layer: WlrLayer.Overlay")
  contains(overview, "Hyprland.toplevels")
  contains(overview, "workspace.active")
  contains(overview, "switcherWindows")
  contains(overview, 'viewMode === "switcher"')
  contains(overview, "function focusedScreen()")
  contains(overview, "screens.length > 0 ? screens[0] : null")
  contains(overview, "visible: root.opened && targetSurface")
  contains(overview, "focusable: targetSurface")
  contains(overview, "WlrKeyboardFocus.OnDemand")
  contains(preview, "import Quickshell.Wayland")
  contains(preview, "ScreencopyView")
  contains(preview, "captureSource: root.capturing ? root.waylandToplevel : null")
  contains(preview, "live: false")
  excludes(overview, "hyprctl")
  excludes(preview, "hyprctl")
end)

t.test("workspace overview implements keyboard-only focus MVP", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")

  contains(overview, "Qt.Key_Left")
  contains(overview, "Qt.Key_Right")
  contains(overview, "Qt.Key_Up")
  contains(overview, "Qt.Key_Down")
  contains(overview, "Qt.Key_Return")
  contains(overview, "Qt.Key_Escape")
  contains(overview, "Qt.Key_Tab")
  contains(overview, "Qt.Key_1")
  contains(overview, "hl.dsp.focus")
  contains(overview, "normalizedAddress")
  contains(overview, "Components.WorkspaceStrip")
  contains(overview, "workspaceEntries")
  contains(overview, "activateWorkspace")
  contains(overview, "showTaskSwitcher")
  contains(overview, "toggleTaskSwitcher")
  contains(overview, "Qt.Key_Meta")
  contains(overview, "handoffToOmarchyMenu")
end)

t.test("workspace overview does not introduce screenshot polling", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")
  local preview = read("quickshell/gendbyte-workspace-overview/components/WindowPreview.qml")

  excludes(overview, "grim")
  excludes(overview, "screenshot")
  excludes(overview, "Timer {")
  excludes(preview, "grim")
  excludes(preview, "screenshot")
  excludes(preview, "Timer {")
  contains(preview, "live: false")
  excludes(preview, "live: root.capturing")
end)


t.test("workspace overview wrapper has race-safe bounded IPC startup", function()
  local wrapper = read("bin/hyprland-workspace-overview")

  contains(wrapper, 'CONFIG_NAME="gendbyte-workspace-overview"')
  contains(wrapper, "STARTUP_ATTEMPTS=100")
  contains(wrapper, "acquire_start_lock")
  contains(wrapper, "wait_for_ipc")
  contains(wrapper, "workspace-overview.log")
  contains(wrapper, 'MODE="${1:-overview}"')
  contains(wrapper, 'task-switcher)')
  contains(wrapper, 'IPC_TOGGLE="toggleSwitcher"')
  contains(wrapper, 'IPC_SHOW="showSwitcher"')
  contains(wrapper, 'ipc "$IPC_TOGGLE"')
  contains(wrapper, 'ipc "$IPC_SHOW"')
end)


t.test("workspace overview strip supports non-contiguous workspaces and add tile", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")
  local strip = read("quickshell/gendbyte-workspace-overview/components/WorkspaceStrip.qml")

  contains(overview, "entries.sort(function(left, right) { return left.id - right.id })")
  contains(overview, "maxId + 1")
  contains(overview, "add: true")
  contains(strip, 'text: modelData.add ? "+"')
  contains(strip, '"New workspace"')
  contains(strip, "activeWorkspaceId")
  contains(strip, "selectedIndex")
end)


t.test("task switcher includes windows from every active monitor workspace only", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")
  local preview = read("quickshell/gendbyte-workspace-overview/components/WindowPreview.qml")

  contains(overview, "var workspace = toplevel.workspace")
  contains(overview, "if (!workspace || !workspace.active)")
  contains(overview, "focusHistoryID")
  contains(overview, "return leftOrder - rightOrder")
  contains(overview, 'readonly property var windowModel: viewMode === "switcher"')
  contains(overview, 'visible: root.viewMode === "overview"')
  contains(overview, '"←→↑↓ select   Enter focus   Esc close"')
  contains(preview, "HoverHandler")
  contains(preview, "selectionRequested")
  contains(preview, "monitorName")
  contains(preview, "workspace.monitor")
end)


t.test("window grid is bounded by a dedicated viewport", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")

  contains(overview, "id: windowViewport")
  contains(overview, "anchors.top: heading.bottom")
  contains(overview, "anchors.bottom: shortcutHint.top")
  contains(overview, "clip: true")
  contains(overview, "gridTargetWidth: windowViewport.width * gridWidthFraction")
  contains(overview, "windowViewport.height")
  contains(overview, "cellWidth")
  contains(overview, "cellHeight")
end)


t.test("workspace overview uses balanced geometry-aware layouts", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")
  local strip = read("quickshell/gendbyte-workspace-overview/components/WorkspaceStrip.qml")

  contains(overview, "if (windowCount === 2)")
  contains(overview, "if (windowCount === 3)")
  contains(overview, "if (windowCount === 4)")
  contains(overview, "if (windowCount <= 6)")
  contains(overview, "return 0.92")
  contains(overview, "return 0.94")
  contains(overview, "return 0.86")
  contains(overview, "function windowAspect(toplevel)")
  contains(overview, "ipc ? ipc.size : null")
  contains(overview, "Math.max(1.15, Math.min(1.90, width / height))")
  contains(overview, "readonly property real sourceAspect: root.windowAspect(modelData)")
  contains(overview, "readonly property real widthFromHeight: maxContentHeight * sourceAspect")
  contains(overview, "readonly property real cardWidth: Math.min(width, widthFromHeight)")
  contains(overview, "readonly property real cardHeight: Math.min(height, contentHeight + titleHeight)")
  contains(strip, "implicitWidth: Math.max(260, workspaceRow.implicitWidth + 34)")
  contains(strip, "implicitHeight: 96")
  contains(overview, "width: Math.min(parent.width, implicitWidth)")
end)


t.test("workspace overview follows active Omarchy palette", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")
  local preview = read("quickshell/gendbyte-workspace-overview/components/WindowPreview.qml")
  local strip = read("quickshell/gendbyte-workspace-overview/components/WorkspaceStrip.qml")
  local theme = read("quickshell/gendbyte-workspace-overview/components/ThemePalette.qml")
  local wrapper = read("bin/hyprland-workspace-overview")

  contains(overview, "Components.ThemePalette")
  contains(overview, "theme.refresh()")
  contains(overview, "theme.background")
  contains(overview, "theme.foreground")
  contains(preview, "property var themePalette")
  contains(strip, "property var themePalette")
  contains(theme, "OMARCHY_THEME_COLORS")
  contains(theme, 'raw.accent || "#ff8a3d"')
  contains(theme, "raw.background")
  contains(theme, "raw.foreground")
  contains(theme, "raw.muted")
  contains(theme, "lighterBackground = mix(background, raisedSource")
  contains(theme, "selection = mix(background, selectionSource")
  contains(theme, "function toColor(value, fallback)")
  excludes(theme, "raw.color8")
  contains(wrapper, 'THEME_COLORS="$STATE_HOME/omarchy/current/theme/colors.toml"')
  contains(wrapper, 'OMARCHY_THEME_COLORS="$THEME_COLORS"')
end)

t.test("Super closes overview and hands release back to existing Omarchy binding", function()
  local overview = read("quickshell/gendbyte-workspace-overview/Overview.qml")
  local bindings = read("hypr/workstation/workspace_overview.lua")

  contains(overview, "event.key === Qt.Key_Meta")
  contains(overview, "root.handoffToOmarchyMenu()")
  contains(overview, "hideOverview()")
  excludes(overview, 'omarchyMenuProcess.exec')
  excludes(bindings, "define_submap")
  excludes(bindings, "opening-guard")
end)
